version: "3"
services:
  git-lfs-server:
    image: ghcr.io/limebit/express-git-lfs:latest
    ports:
      - "8000:8000"
    environment:
      - API_KEY=secret
      - DATA_FOLDER="/service/data"
    # command: yarn run start
    volumes:
      - "./data:/service/data"
